### ISSUE TITLE
WatchNixtoons2 error

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.watchnixtoons2#1]
Hi doko,
FYI. I'm using Leia #0820 (latest Milhouse release) on a RPi3 in LibreELEC.
I'm getting this error message in kodi log when I try to find a cartoon series...

[Code]
12:33:29.412 T:1558180720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: blankCache() takes no arguments (1 given)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/default.py", line 4, in <module>
                                                main() # See bottom of client.py.
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/lib/client.py", line 582, in main
                                                VIEW_FUNCS[params.get('view', 'MENU')](params)
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/lib/client.py", line 325, in viewCatalogSection
                                                cache.ensureCacheLoaded() # Make sure cache is loaded, to avoid web requests.
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/lib/simplecache.py", line 37, in ensureCacheLoaded
                                                self.reloadCache()
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/lib/simplecache.py", line 68, in reloadCache
                                                self.cache = self.blankCache()
                                            TypeError: blankCache() takes no arguments (1 given)
                                            -->End of Python script error report<--
12:33:29.524 T:1549788016   ERROR: GetDirectory - Error getting plugin://plugin.video.watchnixtoons2/?page=0&path=%2fcartoon-list&section=T&view=CATALOG_SECTION
12:33:29.525 T:1938858000   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.watchnixtoons2/?page=0&path=%2fcartoon-list&section=T&view=CATALOG_SECTION) failed[/Code]

BTW, does this release work on your system?

I'll be watching for any updates that you provide.

Later...
Bob

**Comment by doko-desuka** [comment]
I didn't test with Leia yet, that'd be a whole new batch challenges.
Right now I'm more concerned with scraping the right data, making it work at a basic level. Then someone else can work on porting it to Leia,

Someone suggested a different website for scraping, one that has more thumbnails and an easier way to scrape content.
Give it a test if you can:
https://github.com/doko-desuka/plugin.video.toonmania2

**Comment by doko-desuka** [comment]
Oh, forgot to say: movies aren't working right now.
XBMC needs to make it as complicated as it can to just make a simple playlist of items to play... I hope someone else can fix it because I don't want to spend another minute at it =(

**Comment by bjgood** [comment]
Hi doko,
I finally got Toonmania to play a video. It did not play all the videos I selected...just the one. At least a list of different cartoons were listed along with their episode list. Good effort on your part. I'm on Krypton right now.

I've closed the thread.

I'll keep watch on your github to see what else you come up with.

Best regards,
Bob

**Comment by doko-desuka** [comment]
Got it, thanks for testing it again.
I put out another version of toonmania2. I improved the resolvers and some other things. It seems to work better.

**Comment by doko-desuka** [comment]
@bjgood I updated that Toonmania2 these past days, it's got search and genre lists, tons of fixes... if you still use it, you should get the latest version.  
https://github.com/doko-desuka/plugin.video.toonmania2
