### ISSUE TITLE
Repo not updating Watchnixtoons to 2.8. Stuck on 2.7

### ISSUE THREAD

**Issue by PepperHomie** [doko-desuka/plugin.video.watchnixtoons2#10]

**Comment by PepperHomie** [comment]
Looks like the addon is at 2.8 but my repo will only update to 2.7

**Comment by doko-desuka** [comment]
Hm, it's showing 0.2.8 in here:

![watchnixtoons2_0_2_8](https://user-images.githubusercontent.com/31810999/56844318-118bb200-689e-11e9-8d63-640eb3475c96.png)

Try going to your [add-on browser](https://kodi.wiki/view/Add-on_manager#How_to_access_the_Add-on_manager) (it's the box icon, it leads to a menu where you can find commands like "Install from zip file" etc), go to "Install from repository", then long-press / right-click on Doko Repository and select "Check for Updates". This should redownload its addons.xml file that shows the latest WNT2 update.
