### ISSUE TITLE
Trakt icons

### ISSUE THREAD

**Issue by JohnatStile** [doko-desuka/plugin.video.watchnixtoons2#12]
Hi,

First of all thank you everyone who contributed to this fantastic add on. It has been far and beyond the best one I've used for cartoons.

I have a question about having WatchNixToons2 shows the appropriate show icon rather then the generic add-on image. I currently am running 18.2 with Aura skin. I have set up WatchNixToons Trakt list as a widget in the skin however the icons are just the generic Trakt image...I have fanart enabled in the add-on. Any thoughts? It would be great to have the show art show up as the icons instead.

Thanks for any help.

**Comment by doko-desuka** [comment]
Hi @JohnatStile, the Trakt menu is a simple way to quickly search some shows that you have in your Trakt lists.  
When you select an item, it does a name-search (same as if you went to Search -> By Anime/Cartoon Name and typed the name yourself).  

Showing metadata (posters / thumbnails, show descriptions etc.) for these items would be better, but I don't have time to add it for now.   
If anyone can help with that (submitting a pull-request with code for this), I would totally add it.

**Comment by doko-desuka** [comment]
(The reason why it's not a simple thing to do is that there's the question of where this data would come from, as the Trakt API only has text data, no images, so something like the TVDB API would have to be used to find the shows and fetch their posters / thumbnails.)

**Comment by JohnatStile** [comment]
Hi Doko,

Thanks for the response. Unfortunately coding is not my forte but hopefully there is someone out there who could implement it.

Incidentally is there an Openmeta player for WatchNixToons2? This would be a little bit of a work around as you could just create a widget of cartoon trakt lists using OpenInfo (would show all art work, info etc) and then you could just choose the WatchNixToons2 player when you click on the specified cartoon in the widget.

**Comment by doko-desuka** [comment]
Ok, if going the OpenMeta route to access your Trakt lists, then the Trakt handling inside nixtoons2 can be set aside as a to-do for the future.  
I personally don't use OpenMeta, but there was some work done in here: https://www.reddit.com/r/Addons4Kodi/comments/b7fhle/help_creating_a_watchnixtoons2_openmeta_player/ejs4j8k/

You'll need to test what works best for you, ideally incrementing/improving that player based on the docs in here: https://github.com/a4k-openproject/plugin.video.openmeta/wiki/Writing-an-OpenMeta-player  
You can also create reddit topics to ask people for help.
