### ISSUE TITLE
Trakt Lists

### ISSUE THREAD

**Issue by JohnatStile** [doko-desuka/plugin.video.watchnixtoons2#13]
Hi,

I have noticed that the Trakt lists in WatchNixToons2 are only the trakt lists that I (or whoever the account holder is) create themselves. Seren shows Trakt lists which the Trakt account holder just ‘likes’ which is very convenient as it saves you manually creating whole lists yourself.

Is it possible to implement this feature into WatchNixToons2? It would be great to be able to ‘like’, for example, a Disney cartoon Trakt list and then create a WatchNixToons2 widget that list in Aura skin.

Thanks again.

**Comment by doko-desuka** [comment]
Ok, that seems simple enough, showing the lists that the user liked, besides the ones you created yourself.  
I'm still gonna look at this more closely, the following is just a note to myself for later:

```
    def getUserLists(self, addon):
        r1 = self._traktRequest('/users/me/lists', data=None, addon=addon)
        r2 = self._traktRequest('/users/likes/lists', data=None, addon=addon)
        allLists = [ ]
        if r1.ok:
          allLists = r1.json()
        if r2.ok:
          allLists += r2.json()
        return allLists
```
https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/77c7b05a3fb443b0dea5b0246418191bcb053269/Lib/SimpleTrakt.py#L70-L72

https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/77c7b05a3fb443b0dea5b0246418191bcb053269/Lib/Plugin.py#L437

**Comment by JohnatStile** [comment]
Hi Doko,

Thanks for your response and look forward to seeing what you come up with.

**Comment by doko-desuka** [comment]
Added liked lists to the simple Trakt search.

**Comment by JohnatStile** [comment]
Hi,

Thanks for the update. I can now see the Liked lists but when I click on them nothing is populated in them. Lists I have created myself work correctly (although have a strange series of letters after the list name). See link for images: https://imgur.com/a/rEbnerB



Kodi log file: https://paste.kodi.tv/reyufucabe
