### ISSUE TITLE
Cannot Connect to Repository 

### ISSUE THREAD

**Issue by Heioingi89** [doko-desuka/plugin.video.watchnixtoons2#14]
I installed the repo, but get cannot connect to repository? That's the error I get, I have tried on my home wireless network and mobile data. I connect to other repositories fine.

**Comment by doko-desuka** [comment]
Try installing with version 0.1.0 (direct link below):  
https://github.com/doko-desuka/doko.repository/raw/master/doko.repository/doko.repository-0.1.0.zip

There was this version 0.1.55 which is from a time when I didn't yet know that I don't need to update repo versions, only its internal files. So from now on it's going to stay as 0.1.0.
You don't need to uninstall anything, just install from that 0.1.0 and it will overwrite the old repo version.

**Comment by Heioingi89** [comment]
That worked, Thank you so much!
