### ISSUE TITLE
Problem with certain Shaun the Sheep episodes

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.watchnixtoons2#17]
Hey Doko,
I thought I'd point out that Shaun the Sheep episodes 131 through 140 (except for episode 137) gives an error when you try to play them. On the web site they do play.

Here's an error section from kodi.log...
2019-07-27 20:52:46.228 T:1502606208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Default.py", line 4, in <module>
                                                main() # See bottom of Plugin.py.
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Lib/Plugin.py", line 1157, in main
                                                globals()[params.get('action', 'actionMenu')](params) # Defaults to 'actionMenu()'.
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Lib/Plugin.py", line 968, in actionResolve
                                                sourceURL = re.search(b'get\("(.*?)"', r2.content, re.DOTALL).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
2019-07-27 20:52:46.364 T:1937443264   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.watchnixtoons2/?action=actionResolve&url=%2Fshaun-the-sheep-episode-140-bitzers-new-whistle]

The other episode errors are like this one.

Sort of miss seeing your posts, doko, at other sites.

Hope everything is good with you.

As always, the best to you, buddy. :).

Later...

**Comment by doko-desuka** [comment]
Hi. Looks like a variation on the `<iframe>` code, I'll take a look at it later.

**Comment by bjgood** [comment]
Hey doko,
Try the first episode of SpongeBob. BTW, thanks for the Shaun the Sheep fix. It works well so far.

**Comment by doko-desuka** [comment]
Seems other shows stopped working too, others said.

**Comment by bjgood** [comment]
Yeah. I'm experiencing it too.

**Comment by doko-desuka** [comment]
Thanks for the SpongeBob tip, it did show what the problem was. I hope it's working now.

**Comment by bjgood** [comment]
Doko,
It looks like WCO has found a single video of season 1 episode 1. You know, the one with 3 separate chapters (Help Wanted, Reef Blower, and Tea at the Tree Dome). I just went to their site and confirmed it. I didn't help you with anything. I was wondering why WatchNixtoons2 kept telling me there was only one video.

I guess you mean where that episode would not play in 0.3.1.

If I find anything I'll let you know.

Later...

**Comment by doko-desuka** [comment]
That's right, it was failing to play on 0.3.1.

Since it's episode 1 season 1, it's possible WCO wasn't yet doing their thing of splitting the episode into chapters -- maybe in S01E01 they're all in a single long video.

Later
