### ISSUE TITLE
reports of newest version not working 

### ISSUE THREAD

**Issue by SerpentDrago** [doko-desuka/plugin.video.watchnixtoons2#18]
https://old.reddit.com/r/Addons4Kodi/comments/cjf48c/watchnixtoons_2_not_playing_anything/

**Comment by doko-desuka** [comment]
Thanks for the report, I can take a look tomorrow.

**Comment by bjgood** [comment]
SerpentDrago showed the folks over at Reddit how to step down to 3.0. I didn't even know how to do that.

**Comment by doko-desuka** [comment]
Yeah, if you install any old version it will overwrite the current one.  
But if you have auto-updates on, whenever Kodi updates the add-on it will overwrite your forced install of the old.

Anyway, things should be working now. I'm closing this but if there's something wrong do tell.

**Comment by doko-desuka** [comment]
Direct link: [plugin.video.watchnixtoons2-0.3.2.zip](https://github.com/doko-desuka/plugin.video.watchnixtoons2/raw/master/plugin.video.watchnixtoons2-0.3.2.zip)
