### ISSUE TITLE
Liked Trakt Lists not populating 

### ISSUE THREAD

**Issue by JohnatStile** [doko-desuka/plugin.video.watchnixtoons2#19]
Hi,

Thanks for the update. I can now see the Liked lists but when I click on them nothing is populated in them. Lists I have created myself work correctly (although have a strange series of letters after the list name). See link for images: https://imgur.com/a/rEbnerB

Kodi log file: https://paste.kodi.tv/reyufucabe

Running Kodi 18.3, Auramod skin and latest WatchNixToons2 Addon.

**Comment by doko-desuka** [comment]
Hi @JohnatStile, I have fixed the list display.  
You should be getting an update, let me know if anything's still not working (in which case please open another issue).

**Comment by JohnatStile** [comment]
Hi @doko-desuka,

Thanks. It seems to be functioning correctly now. Thanks again.
