### ISSUE TITLE
Strip out some of the info in an episodes list

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.watchnixtoons2#2]
Hey doko,
It would be nice if you could remove the series name from the episodes list. Shorten each episodes listing just a bit. For example..."Garfield and Friends Season 1 Episode 1 Peace and Quiet/Wanted:Wade/Garfield goes Hawaiian" to "Season 1 Episode 1 Peace and Quiet/Wanted:Wade/Garfield goes Hawaiian". Better yet, "S1xE1 Peace and Quiet/Wanted:Wade/Garfield goes Hawaiian". I know the latter would be difficult to do.

I looked your code over but could not find where just the series name was used when building the directory for a series.

I hope I explained this request well enough.

As you said, it certainly was a total re-write of WatchNixtoons. Congrats for the innovation.

Also, where are you storing the data for each series to reduce the requests from WatchCartoonOnline and the mobile version? It's not in addon_data>plugin.video.watchnixtoons2 that I could see.

Later...

**Comment by bjgood** [comment]
Nevermind about the "storing the data for each series" part of my above post. I read where it's stored in memory temporarily.

Thanks, doko. :).

**Comment by doko-desuka** [comment]
Hi @bjgood, thanks for testing.  
At the moment the episode names are being used as they are (the link text just used as the label).  
I think it's possible to strip the series name from those labels, the relevant code is in function 'makeListItem', I'll give it a look.  

As for caching, it stores in memory only (no files), which I guess is better than no caching at all. You can search for the calls to 'setWindowProperty' to find where it happens (getCatalogProperty and actionEpisodesMenu functions).

**Comment by doko-desuka** [comment]
@bjgood okay, I added a "Clean Episode Titles" setting, the default is off (so it doesn't affect the people that don't know about it).  
I don't really want to dedicate more time for this -- since it's a customization and I personally don't have a need for it -- so if you want the formatting done in different ways, feel free to go in the [makeListItemClean() function](https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/Lib/Plugin.py#L469-L470) and further customize it.  
I hope it works better now.  
Regards.

**Comment by bjgood** [comment]
Thanks, for your efforts, doko. I'll try not to bother you again concerning this addon and cosmetic changes.

**Comment by bjgood** [comment]
Just wanted to add that it's working great. Thanks. The only thing I changed was the zfill digit from 2 to 1. I don't see how you accomplished all that with so few lines. In the Nixtoons version I have a whole list of alterations to the code to achieve what you did. Try not to be too pissed.

Later...

**Comment by doko-desuka** [comment]
Great to know that it's working.  
That .zfill() function is pretty awesome, first time I'd ever used it.  
I also noticed that using regex (from the 're' module) instead of BeautifulSoup for scraping the web pages is much faster.
