### ISSUE TITLE
Search History 

### ISSUE THREAD

**Issue by rogermae** [doko-desuka/plugin.video.watchnixtoons2#20]
Would like to see a search history added to all the folders(?)

**Comment by doko-desuka** [comment]
And I'd like to see other people volunteering to help add features hehe...  

This is the most I can do for now, it remembers the Cartoon/Anime, Movie and Episode searches. 
![searchHistoryTemp](https://user-images.githubusercontent.com/31810999/62825394-2eb06c00-bb81-11e9-98f1-d5ed456268cc.png)

If someone else wants to improve on it, I promise to take a look at any pull-requests.

**Comment by rogermae** [comment]
Thanks

Kind Regards,
Roz

________________________________
