### ISSUE TITLE
Episodes only loading first part when its a two part episode

### ISSUE THREAD

**Issue by choppywordsinasloppyflow** [doko-desuka/plugin.video.watchnixtoons2#21]
There's an issue where the addon only finds the first part of an episode on some shows. For example, My Life As A Teenage Robot episode 1 is labeled “It Came from Next Door/Pest Control”, but will only find “It Came from Next Door”. SpongeBob also has this problem where it only finds part A of an episode and not B,. However, this isn't a problem with every cartoon that has two parts in one episode, shows like Hey Arnold and Rugrats will find parts A and B of the episode

**Comment by doko-desuka** [comment]
It's inconsistent alright, I wish they had a simpler way of showing different chapters.  
But anyway, we can't complain from freeloading their videos -_-'

The solution the add-on uses is a context-menu. Right-click (on desktop) or long-press (on Android/touch devices) on the list item such as Episode 1, and choose Play Chapters, then choose any of the two items.  

If there's still a problem you can still comment on this issue, even though I closed it

**Comment by doko-desuka** [comment]
Hm, actually this might help others, so I'm leaving this issue open as sort of a guide.

**Comment by bjgood** [comment]
Hey Doko,
As I have commented before, and this issue demonstrates, you should revert to the way you had it in 0.2.8 when if the addon notices two distinct chapters it displays the dialog box for those chapters automatically. It would make everything much more intuitive for the user. And, it would do away with the need for a context menu entry.

Have a good one.

**Comment by doko-desuka** [comment]
@bjgood if you find a bug with this do tell:
https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/addon.xml#L15

**Comment by bjgood** [comment]
Hey Doko,
I am truly shocked. You actually listened to me. I'll have to write this down on a calender. ;).

The settings addition for multi-chapters is a good way to approach it. The word of this change will need to be gotten out, though, for no one will know it's there. And, so far so good with reference to its functioning.

I'll let you know if I run across any errors or malfunctions.

Thanks, doko, for this.

Later, bud.
