### ISSUE TITLE
Trakt

### ISSUE THREAD

**Issue by latiku3** [doko-desuka/plugin.video.watchnixtoons2#23]
All I see in the Trakt panel is "clear trakt tokens", how do I add it so watched content is synced to trakt?

**Comment by doko-desuka** [comment]
The Trakt functionality is very simple and is accessed in Search -> Search by Trakt List  
This is a convenience to search the names of items you have in your lists. It does the same as a name search, as if you typed the name manually.

To sync watched content, or at least add a context menu that lets you tag your Trakt items as watched, would require extra code that I don't have time to add right now. If anyone wrote the code for that I would gladly add it, but I guarantee you nobody will.

**Comment by doko-desuka** [comment]
I added an 'About...' button to the Trakt category of the settings explaining how to use it, so I can now close this.
