### ISSUE TITLE
Not getting new episodes

### ISSUE THREAD

**Issue by PepperHomie** [doko-desuka/plugin.video.watchnixtoons2#24]
My hero academia and sword art online havent pulled the newest episodes yet

**Comment by doko-desuka** [comment]
This add-on grabs content from an external website that is not managed by me. I have no way to add new episodes. Maybe WonderfulSubs already has them?

**Comment by PepperHomie** [comment]
I apologize.  I checked the site after I commented. It's not on the site you scrape it from. Very odd. Seems like the site is missing a good amount of shows after last friday.

**Comment by doko-desuka** [comment]
No problem, thanks for the report anyway.  
[WonderfulSubs](https://www.reddit.com/r/WonderfulSubs/wiki/kodi) seems to have 4x01 sub, and I also see there's episodes 4x01 and 4x02 in swatchseries, a generic TV-series website accessible from an add-on like ScrubsV2.

**Comment by doko-desuka** [comment]
It seems they added 4x01 and 4x02 of Boku No Hero Academia. They also changed the website domain, I'll put an update out for that.
