### ISSUE TITLE
Cover art no longer being pulled

### ISSUE THREAD

**Issue by PepperHomie** [doko-desuka/plugin.video.watchnixtoons2#25]
When you use the show information feature none of the cover art is pulled. I know you changed the url that this stuff is scraped from but now it wont pull the cover art from there.

**Comment by doko-desuka** [comment]
Hi @PepperHomie, thanks for the report. Version 0.3.7 should have fixed this.

**Comment by PepperHomie** [comment]
When do you think that will release?

**Comment by doko-desuka** [comment]
That moment I posted was right after I submitted the release.  
If you have my repo you should be getting the update automatically. If not, you can manually install it with this zip file: https://github.com/doko-desuka/plugin.video.watchnixtoons2/raw/master/plugin.video.watchnixtoons2-0.3.7.zip
