### ISSUE TITLE
Not working check error log

### ISSUE THREAD

**Issue by itsacuppycake** [doko-desuka/plugin.video.watchnixtoons2#26]
No episodes will play, was working fine last night

**Comment by doko-desuka** [comment]
I'm on Kodi 17.6 and I tested SpongeBob 7x11 and Boruto subbed 1x03, both worked.

Did you check your log? What does it say? (do it right after the error happens so it's quicker to find at the end of the log.)  
What Kodi version are you using?  
Did you update any add-ons at all, or did any system updates on your device?  
What show and episode are you trying to play?

**Comment by PepperHomie** [comment]
> I'm on Kodi 17.6 and I tested SpongeBob 7x11 and Boruto subbed 1x03, both worked.
> 
> Did you check your log? What does it say? (do it right after the error happens so it's quicker to find at the end of the log.)
> What Kodi version are you using?
> Did you update any add-ons at all, or did any system updates on your device?
> What show and episode are you trying to play?

I'm also getting the issue
Error:Playlist Error: skipping unplayable  item: 0, path [Plugin://Plugin.video.watchnixtoons2/?action=actionResolve&url=%2assassination-classroor


The error path ends right there. Very odd it doesnt show the whole file path. The bracket never closes.

**Comment by PepperHomie** [comment]
It could be related to favoriting a show. The error seems to fix it self if I research for the show in the watchnixtoons addon  when booting up kodi rather than trying to access the show from my favorites section in kodi. I also noticed it hasnt been pulling quality links and just trying to play the show without you choosing if you want 480p or 720p. That's all I can tell you. Hope it helps. Let me know if I can test anything

**Comment by PepperHomie** [comment]
I will have to check what version of kodi I'm on when I get home. Its whatever the newest release of kodi is on xbox one. This error happens on all shows when its happening

**Comment by doko-desuka** [comment]
@PepperHomie thanks for the coming in with information.  
When it plays without letting you choose the quality it's because it only found one quality (so no need to let you choose it).  
Playing from favorites... that would make sense to crash if I save the entire link in the list item (I don't remember from head), so your favorites carry the old domain instead of the new one. I'll add a safety check.

**Comment by doko-desuka** [comment]
Oh, and error messages in Kodi usually take up several lines, they also show the section of code that crashed.

**Comment by PepperHomie** [comment]
> @PepperHomie thanks for the coming in with information.
> When it plays without letting you choose the quality it's because it only found one quality (so no need to let you choose it).
> Playing from favorites... that would make sense to crash if I save the entire link in the list item (I don't remember from head), so your favorites carry the old domain instead of the new one. I'll add a safety check.

I did a fresh install of kodi and watchnixtoons yesterday so these favorites were made yesterday night. Let me know what you find

**Comment by doko-desuka** [comment]
I sent out update 0.3.8. I tested some more and things are working here, favorites included. If it still doesn't work then it's something changed in your Kodi version (I know that v19 has breaking-changes, with Python 3).

**Comment by PepperHomie** [comment]
> I sent out update 0.3.8. I tested some more and things are working here, favorites included. If it still doesn't work then it's something changed in your Kodi version (I know that v19 has breaking-changes, with Python 3).

Alright do I need to refavorite my anime after updating? Also if the original poster would tell us if he had the issue with his favorites or just standard usage that would really help.

**Comment by doko-desuka** [comment]
I don't think you do, if they point to the old site, the add-on now corrects it with the new site.  
I'm closing this issue, but feel free to keep commenting here (i.e if @itsacuppycake still has an error, for example, I'll reopen this issue).

**Comment by itsacuppycake** [comment]
@doko-desuka thank you it's fixed! Sorry for the late response, fell asleep. I'm on fire stick and most recent/updated version. I was trying to access the videos from my favorites. (Also wasn't working when I looked up a random anime though) I just checked and im now able to get to anything from my favorites list without having to update anything. Thanks for all the awesome stuff you do you're the shit 😄
