### ISSUE TITLE
Watchnixtoons2 doesn't work

### ISSUE THREAD

**Issue by ShakarSaleem** [doko-desuka/plugin.video.watchnixtoons2#28]
Hello, watchnixtoons2 doesn't seem to be working I click on a show, it loads then stop. It does not play the show.

**Comment by doko-desuka** [comment]
Watch show and episode are you trying to watch?

**Comment by ShakarSaleem** [comment]
All in dubbed, black clover episode 112 one piece episode 211.

**Comment by ShakarSaleem** [comment]
These are in the dub section

**Comment by doko-desuka** [comment]
Try to watch it in the original website (you can find it in [this page](https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/README.md)).  
It's not playing there either. The error seems to be on their end, with their server not giving out a video link.

**Comment by ShakarSaleem** [comment]
Your right it's not working on their end, which sucks I'll just have to wait it out thanks for the good work you do

**Comment by doko-desuka** [comment]
Hopefully when they fix that, the add-on should work again

**Comment by ShakarSaleem** [comment]
All is back to normal.

**Comment by doko-desuka** [comment]
Great, thanks for reporting back.
