### ISSUE TITLE
WatchNixtoons2 some shows show no episodes

### ISSUE THREAD

**Issue by itsacuppycake** [doko-desuka/plugin.video.watchnixtoons2#29]
Went to Kimetsu No Yaiba (dubbed) and no episodes showed up, at first I did this from my favorites list and then looked it up alphabetically, only the " ... " Show which takes you back to the main menu of Nixtoons. Looks like other animes work but also tried My Hero and same issue. Updated Kodi too and that didn't help either ):

**Comment by madeira83** [comment]
I'm getting the same issue with those anime as well as One Piece and some others. I also thought it was an issue from accessing it from favs but then i was getting the issue directly accessing it from the addon. Thanks.

**Comment by itsacuppycake** [comment]
@madeira83 yes it seems like it's the more popular animes that are messing up cause I tried a couple different animes at random off the list and they seemed to be working. Guess I'm gonna have to try something new for now 😂

**Comment by doko-desuka** [comment]
Hi guys.  
It's a server issue, as it's happening when you use the mobile version on a browser. I sent them an email, hope they fix.  
If they don't I will change the add-on to use the full website version anyway.

**Comment by doko-desuka** [comment]
(The mobile version of the source website that is, like when you go to it with a tablet.)

**Comment by d1arkstar** [comment]
@doko-desuka  thank you for the update I do like your app does take a little of getting  use to but works well

**Comment by itsacuppycake** [comment]
@doko-desuka  thank you for the update 😊

**Comment by doko-desuka** [comment]
Okay, changed the add-on to always use the desktop version of the website, ignoring the mobile version for now (at least until they fix it). So it's working.  
You can get the latest version from [the repository](https://github.com/doko-desuka/doko.repository/releases) or from the link on the [add-on description page](https://github.com/doko-desuka/plugin.video.watchnixtoons2).

**Comment by doko-desuka** [comment]
Heh, a few hours later they replied:  
> Hi,
>
> we had a temporary problem, now that should be fixed.
> 
> \- Yandere Victim (Admin) \-

**Comment by madeira83** [comment]
Hi @doko-desuka I'm using the kodi addon and i'm still having the same problem right now with Boruto, My Hero and One Piece.

**Comment by doko-desuka** [comment]
@madeira83 did you update it to the latest? It's on v0.3.9 at the moment.

**Comment by madeira83** [comment]
I will check. Maybe thats it. Thanks.

**Comment by d1arkstar** [comment]
@doko-desuka  thank you for the fast fix

**Comment by itsacuppycake** [comment]
@doko-desuka thank you!!

**Comment by madeira83** [comment]
Confirmed fix as well. thanks!
