### ISSUE TITLE
Some shows are not working

### ISSUE THREAD

**Issue by ezkiolandgaming** [doko-desuka/plugin.video.watchnixtoons2#32]
Some shows like Pokemon, Batman, or boruto: next generations won't load the episode list showing a error when it is attempted to be loaded. Not sure the cause as since I watch Kodi from a Amazon stick so am unable to find out how to load logs.

**Comment by doko-desuka** [comment]
The homepage of their website isn't loading, it's giving a HTTP 502 error.  
It's something on their end, nothing I can do from here.

**Comment by doko-desuka** [comment]
Hm, actually, there might be. They have different domains, and one of the domains seems to be loading. I'll try something.

**Comment by doko-desuka** [comment]
Ok, so no thing is needed. I just tested and the Boruto: Next Generations that you reported did play on episode 139 subbed, and episode 46 dubbed. So I'm considering this solved for the moment, please open a new issue if it comes back.
