### ISSUE TITLE
New episodes not showing up 

### ISSUE THREAD

**Issue by PepperHomie** [doko-desuka/plugin.video.watchnixtoons2#33]
Black clover episode 121 is out on https://m.wcostream.com/ but is not showing up in the add on. This might be the same for other new episodes.

**Comment by Cryptonite26** [comment]
I can see episode 121 of black clover on the addon just fine?

**Comment by doko-desuka** [comment]
This is a problem with their website. You should try [sending them an email](https://www.wcostream.com/contact), saying "I can see ep. 121 on your mobile site but not desktop site, can you fix that?".

Besides that, you can also try changing this line here...  
https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/Lib/Plugin.py#L30
...to use the domain `https://www.wco.tv`.  
It's one of their many domains and it does contain episode 121 of that series.

**Comment by PepperHomie** [comment]
> This is a problem with their website. You should try [sending them an email](https://www.wcostream.com/contact), saying "I can see ep. 121 on your mobile site but not desktop site, can you fix that?".
> 
> Besides that, you can also try changing this line here...
> https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/Lib/Plugin.py#L30
> ...to use the domain `https://www.wco.tv`.
> It's one of their many domains and it does contain episode 121 of that series.

That shouldn't be my job to do no offense. It shouldn't be too hard to compare desktop site and mobile and if the list size is bigger in one just show the bigger selection.

**Comment by doko-desuka** [comment]
That would be making the add-on go out of its way to account for their inability to keep all of their domains synchronized. I'm against anyone spending their free time to make code to fix that (better to spend it with an add-on for a site that's more organized).

On another note, I've found myself running out of time to keep reviewing bug reports. I've been thinking for some time of archiving this repo. I hope someone else can take over it =(

**Comment by mrferdinand** [comment]
Please don't feel that way doko. Every time I've used the add-on even back
when it first dropped, I never had an issue. Most of the time, I've noticed
the main issues are from the main website. People using the add-on just
need to do more troubleshooting on their part in order to rule out user
error. Thank you for all your hard work.

**Comment by PepperHomie** [comment]
> That would be making the add-on go out of its way to account for their inability to keep all of their domains synchronized. I'm against anyone spending their free time to make code to fix that (better to spend it with an add-on for a site that's more organized).
> 
> On another note, I've found myself running out of time to keep reviewing bug reports. I've been thinking for some time of archiving this repo. I hope someone else can take over it =(

Well in general you should design it to account for that. If it's something you want to abandon then wouldn't you want it to handle issues like this? I understand that the fix for this may cause watchnixtoons to load slower but to better its efficiency then it should be worth it. You know I help you with error reporting and what not before to solve issues but I'm just saying if it's going to be a constant issue then people may see just going to the site or using another add on as a better option.

**Comment by Cryptonite26** [comment]
I really enjoy this addon. I really hope people stop annoying you with unnecessary issues and focus on actual bugs not related to the website not being updated itself.

**Comment by PepperHomie** [comment]
> I really enjoy this addon. I really hope people stop annoying you with unnecessary issues and focus on actual bugs not related to the website not being updated itself.

It's not uneccesarry. It's basic error handling that should be implemented if he plans to abandon the add on.

**Comment by Cryptonite26** [comment]
> This is a problem with their website. You should try [sending them an email](https://www.wcostream.com/contact), saying "I can see ep. 121 on your mobile site but not desktop site, can you fix that?".
> 
> Besides that, you can also try changing this line here...
> https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/Lib/Plugin.py#L30
> ...to use the domain `https://www.wco.tv`.
> It's one of their many domains and it does contain episode 121 of that series.

Hi Doko, I'n sorry to bother you again with regards to this, but I'm trying to use the URL I've always used from them however when I try opening any episode list (the shows appear) I get an error.

I'm trying to use thewatchcartoononline.tv as my base URL since it seems to have a lot less issues but this is my first time ever using python. and I want to try and figure some stuff out so that I can maybe contribute to simple fixes for silly things like domain changes and such. but for the life of me I can't figure out what I did wrong here.

[kodi.log](https://github.com/doko-desuka/plugin.video.watchnixtoons2/files/4198063/kodi.log)
[plugin.video.watchnixtoons2.zip](https://github.com/doko-desuka/plugin.video.watchnixtoons2/files/4198064/plugin.video.watchnixtoons2.zip)

**Comment by PepperHomie** [comment]
> > This is a problem with their website. You should try [sending them an email](https://www.wcostream.com/contact), saying "I can see ep. 121 on your mobile site but not desktop site, can you fix that?".
> > Besides that, you can also try changing this line here...
> > https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/Lib/Plugin.py#L30
> > ...to use the domain `https://www.wco.tv`.
> > It's one of their many domains and it does contain episode 121 of that series.
> 
> Hi Doko, I'n sorry to bother you again with regards to this, but I'm trying to use the URL I've always used from them however when I try opening any episode list (the shows appear) I get an error.
> 
> I'm trying to use thewatchcartoononline.tv as my base URL since it seems to have a lot less issues but this is my first time ever using python. and I want to try and figure some stuff out so that I can maybe contribute to simple fixes for silly things like domain changes and such. but for the life of me I can't figure out what I did wrong here.
> 
> [kodi.log](https://github.com/doko-desuka/plugin.video.watchnixtoons2/files/4198063/kodi.log)
> [plugin.video.watchnixtoons2.zip](https://github.com/doko-desuka/plugin.video.watchnixtoons2/files/4198064/plugin.video.watchnixtoons2.zip)

You can't just plug in any sites domain that has anime on it. He said to use one of their other domains at line 30. The one you used does not look like their site so it would need more configuration for it to work.

**Comment by Cryptonite26** [comment]
> > > This is a problem with their website. You should try [sending them an email](https://www.wcostream.com/contact), saying "I can see ep. 121 on your mobile site but not desktop site, can you fix that?".
> > > Besides that, you can also try changing this line here...
> > > https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/Lib/Plugin.py#L30
> > > ...to use the domain `https://www.wco.tv`.
> > > It's one of their many domains and it does contain episode 121 of that series.
> > 
> > 
> > Hi Doko, I'n sorry to bother you again with regards to this, but I'm trying to use the URL I've always used from them however when I try opening any episode list (the shows appear) I get an error.
> > I'm trying to use thewatchcartoononline.tv as my base URL since it seems to have a lot less issues but this is my first time ever using python. and I want to try and figure some stuff out so that I can maybe contribute to simple fixes for silly things like domain changes and such. but for the life of me I can't figure out what I did wrong here.
> > [kodi.log](https://github.com/doko-desuka/plugin.video.watchnixtoons2/files/4198063/kodi.log)
> > [plugin.video.watchnixtoons2.zip](https://github.com/doko-desuka/plugin.video.watchnixtoons2/files/4198064/plugin.video.watchnixtoons2.zip)
> 
> You can't just plug in any sites domain that has anime on it. He said to use one of their other domains at line 30. The one you used does not look like their site so it would need more configuration for it to work.

https://m.wcostream.com/important-regarding-to-fake-sites-all-visitors-please-read

it is one of their domains.

**Comment by doko-desuka** [comment]
@Cryptonite26 that domain you said, www dot thewatchcartoononline dot tv, seems to have a slightly different HTML than the one in the address the add-on is using, that's why plugging it in doesn't work.  
But it had Black Clover ep. 121 and is one of their "generic" domains that has all three types of content (cartoon, movies/ovas and anime-sub/anime-dub), so it seems to be more updated.

I changed the add-on to use that new domain, it's WNT2 v0.4.1.  
The scraping for all categories (movies, anime, cartoons etc.) had to be updated, so if it's all working properly then this version should last for a long while.

**Comment by PepperHomie** [comment]
> @Cryptonite26 that domain you said, www dot thewatchcartoononline dot tv, seems to have a slightly different HTML than the one in the address the add-on is using, that's why plugging it in doesn't work.
> But it had Black Clover ep. 121 and is one of their "generic" domains that has all three types of content (cartoon, movies/ovas and anime-sub/anime-dub), so it seems to be more updated.
> 
> I changed the add-on to use that new domain, it's WNT2 v0.4.1.
> The scraping for all categories (movies, anime, cartoons etc.) had to be updated, so if it's all working properly then this version should last for a long while.

Just a heads up, moving forward with this version. Pre-existing favorites will become obsolete and you will need to find and favorite them again in the updated addon. The old favorites will work but will not pull missing shows like black clovers episode 121.

**Comment by Cryptonite26** [comment]
> @Cryptonite26 that domain you said, www dot thewatchcartoononline dot tv, seems to have a slightly different HTML than the one in the address the add-on is using, that's why plugging it in doesn't work.
> But it had Black Clover ep. 121 and is one of their "generic" domains that has all three types of content (cartoon, movies/ovas and anime-sub/anime-dub), so it seems to be more updated.
> 
> I changed the add-on to use that new domain, it's WNT2 v0.4.1.
> The scraping for all categories (movies, anime, cartoons etc.) had to be updated, so if it's all working properly then this version should last for a long while.

thank you very much for the help.. I'm going to attempt to do some more research on how exactly the code should change and will try to help out with domain changes in the future if it would be necessary but I've been using that domain for quite a few years without trouble (albeit the domain changed a tad bit last year) so it should be good now thanks a million!
