### ISSUE TITLE
Losing watched episodes

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.watchnixtoons2#34]
Hi Doko,
For versions 0.4.0 and 0.4.1 we having been losing our watched episodes check marks for a series. Can you think of any reason why WatchNixtoons2 would be doing that? Luckily we have been able to remember which episodes we viewed last.

Thank you.

**Comment by Cryptonite26** [comment]
> Hi Doko,
> For versions 0.4.0 and 0.4.1 we having been losing our watched episodes check marks for a series. Can you think of any reason why WatchNixtoons2 would be doing that? Luckily we have been able to remember which episodes we viewed last.
> 
> Thank you.

Hi bjgood. That would be because version 0.4.0 and v 0.4.1 are directing to different domains with a slightly different HTML version so the categories had to be rewritten for 0.4.1 to work. The reason for the domain switch is because the domain that 0.4.0 was directing to (wcostream.com) had a slightly outdated database compared to the newer thewatchcartoononline.tv

**Comment by bjgood** [comment]
> appologies this is mostly my fault since I suggested the domain change.

First off, thanks for the reply. And, no need to apologize.

Since the domain change was necessary, then no problem on my part. Like I said, we were able to remember the last episodes we watched for a given series.

Thanks for the explanation. But, I half way suspected that was the reason.

Have a good one.

**Comment by doko-desuka** [comment]
That's an interesting side effect, good catch.

**Comment by bjgood** [comment]
Hi Doko, :)
Where the hell you've been keeping yourself?
Have a good one.
Later...

**Comment by doko-desuka** [comment]
@bjgood hi man. I'm doing fine, how about you?
I hope the new "[restore watched episodes](https://github.com/doko-desuka/plugin.video.watchnixtoons2/pull/35#issue-375845532)" tool works, I had never thought updating the site address would cause such a thing.
