### ISSUE TITLE
Video playback error

### ISSUE THREAD

**Issue by northstargundam** [doko-desuka/plugin.video.watchnixtoons2#37]
Whenever I try to play a current anime nothing loads after the quality selection screen. All it does is the load icon spins once or twice and nothing happens or I het the message "one or more items failed to play. Check the log for more info." It works fine if it is an older anime or cartoon but nothing current will load.
![0320201449_HDR](https://user-images.githubusercontent.com/62444322/77197880-53c47000-6abc-11ea-9ff1-e81a5e023131.jpg)

**Comment by doko-desuka** [comment]
Hi. It played the 480p subbed and dubbed versions of "Plunderer Episode 11" in here (I didn't try the 720p), so there must be something obscure going on with your circumstances over there that doesn't make it work.  
But the add-on is getting the video streams properly, so there's not much to go on.  I'll be closing this, but feel free to comment further.

**Comment by northstargundam** [comment]
I tried It on 480p and same thing. I use this add on on 2 devices (xbox1,Firestick) and same messages on both

**Comment by doko-desuka** [comment]
Have you tried watching it on the original website?  
https://dereferer.me/?https%3A//www.thewatchcartoononline.tv/plunderer-episode-11-english-subbed

**Comment by northstargundam** [comment]
The site works fine, but still doesn't work on my fire stick or Xbox 1. The wonderful subs add on works just not the nixtoons2. Started having similar issues with other addons. I uninstalled kodi and put it back on and that did nothing so who knows what's going on

**Comment by doko-desuka** [comment]
Someone had a similar problem with WNT2 like you, they found it was because they were being geoblocked.  

They solved it by going to their device's network settings and changing the (primary) DNS address to 1.1.1.1 -- This is Cloudflare's public DNS, supposedly it's very fast and safe. Worth a try.

**Comment by northstargundam** [comment]
Still no luck, is the add on compatible with kodi Leia 18.6

**Comment by doko-desuka** [comment]
It should be.  
If you can, send me your full Kodi log (as soon as the error happens) to...  
dokodesuka121 at gmail dot com

...and I'll take a look.
