### ISSUE TITLE
Updated to 4.4 and not working?

### ISSUE THREAD

**Issue by Cjhewison** [doko-desuka/plugin.video.watchnixtoons2#38]
Updated to your latest and its stopped working. Don't know if it'll make much difference but im using a firestick

**Comment by doko-desuka** [comment]
@Cjhewison describe the problem in more detail. Where does it fail, what menu? Are you trying to play something, what show and episode?

**Comment by doko-desuka** [comment]
Hi, please see this:  
https://www.reddit.com/r/Addons4Kodi/comments/fr23db/need_help_with_nixtoons_nothing_is_playing_1/
