### ISSUE TITLE
WatchNixtoons2 is down

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.watchnixtoons2#4]
Doko,
It looks like WatchNixtoons2 is down. In the kodi log it's giving this error...

                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Default.py", line 4, in <module>
                                                main() # See bottom of Plugin.py.
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Lib/Plugin.py", line 1027, in main
                                                globals()[params.get('action', 'actionMenu')](params) # Defaults to 'actionMenu()'.
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Lib/Plugin.py", line 877, in actionResolve
                                                sources = json.loads(temp.replace("'",'"'))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded

Don't know how long it has been this way. We haven't tried watching it any until now. The series-episode we tried to watch was Adventure Time 7x38-39. Other episodes will not play, as well. Other series, too. On the website they do play.

**Comment by Wolfhouser** [comment]
Yeah mines not working either. Was working all ok last night for me. Went on this morning to watch My Hero Academia s02e13 and it’s giving me the same error.

**Comment by doko-desuka** [comment]
Thanks for the log, saves time.  
It was a change of the media request routes. See if 0.2.4 is working (commit 
https://github.com/doko-desuka/plugin.video.watchnixtoons2/commit/4b598e8a86cd24b554582947b3045c2f61ef934a), and if so, please close this.

**Comment by doko-desuka** [comment]
Oh and @bjgood since you made some modifications to yours (that special title handling), I suggest backing it up before updating, because an update would overwrite that.  
If you think the title stuff is decently coded you can also submit it as a PR.

**Comment by Wolfhouser** [comment]
Hey @Doko-desuka any chance 0.2.4 will be rolled out as an update for fire stick once it’s ready?

**Comment by bjgood** [comment]
Doko,
Thanks for the fix. It's working. Closing issue.

Thanks, buddy.

**Comment by bjgood** [comment]
Wow! I looked at your commit for this fix. That's a lot of work you had to do there, bud.

**Comment by doko-desuka** [comment]
> Hey @doko-desuka any chance 0.2.4 will be rolled out as an update for fire stick once it’s ready?

Yes, it's packaged and sent as an update. You should be seeing it on your end, in Kodi. In case it doesn't detect the update right away, try updating doko-repository or downloading the wnt2 zip directly.

> Wow! I looked at your commit for this fix. That's a lot of work you had to do there, bud.

Aye lol. It was =(

**Comment by bjgood** [comment]
Doko,
Will WatchNixtoons2 work in Krypton? I know it does in Leia. I'm running Krypton on a Firestick still. Leia bogs down a Firestick too much for it to function smoothly.

**Comment by doko-desuka** [comment]
Wnt2 was created and tested using Krypton (17.6), if it works on Leia (18+) then that's luck.

**Comment by bjgood** [comment]
Doko, we got a problem. Some series will play (like T.U.F.F Puppy, Shaun the Sheep, All Hail King Julien, The Mighty B, Monsters vs Aliens) while others will not (like Adventure Time, Garfield and Friends, Men in Black, Back at the Barnyard, The Penguins of Madagascar, The Smurfs). The ones that will not play act like they want to play but kick out after the busy animation twirls a couple of times. The ones that do play...it's business as usual.

If you need anything additional just let me know.

**Comment by doko-desuka** [comment]
Hm, some of those seem to use a different host. To help with debugging, out of the non-working shows can you list some episode(s) that fail(s)?
I'm on a different PC than the one I work on Kodi plugins, I can look at this tomorrow.

**Comment by doko-desuka** [comment]
Oh, okay. They try one host, and if that doesn't work then they try another one, like a backup host.  
I'll add that in tomorrow.

**Comment by bjgood** [comment]
On a series, like Garfield and Friends, or any of the others I listed, no episodes play (at least any of the ones I tried). I didn't try every episode of a series.

Later, Doko.

**Comment by bjgood** [comment]
When you have some free time I have a doozy of a problem for you to solve in WatchNixtoons2. Look SpongeBob Squarepants, the series, over. Each episode consists of two, or three separate videos. In the series list it shows the episode title for each segment, but the the addon only plays the first segment/video.

Like I said, a doozy of a problem. Wonder if you can solve it?

Later, Doko. :).

**Comment by daniel-ntl** [comment]
i will try your fix thx

**Comment by doko-desuka** [comment]
Try 0.2.5.

**Comment by bjgood** [comment]
As of right now it seems to be a success. All series that were not playing previously are playing now.

Congrats.

BTW. Look SpongeBob SqurePants over before you get too cocky. :).

**Comment by ShakarSaleem** [comment]
Hi guys the doku comment area I think it's called is closed and some say that watchnixtoons and watchnixtoons2 are back up and running but on 2 when I load an episode of a certain magical index which is SD I set the option of that and 720 too on normal watchnixtoons add-on the dialogue box appear without an option to choose the quality any ideas thanks

**Comment by ShakarSaleem** [comment]
some say that watchnixtoons and watchnixtoons2 are back up and running but on 2 when I load an episode of a certain magical index which is SD I set the option of that and 720 too on normal watchnixtoons add-on the dialogue box appear without an option to choose the quality any ideas

**Comment by bjgood** [comment]
I guess you already looked at SpongeBob, because it's working really good with the dialog box popping up and everything. Nice coding, Doko. I never expected you to even try it. Congrats again.

Highly surprised is putting it mildly.

Thank, Doko.

**Comment by doko-desuka** [comment]
> on normal watchnixtoons add-on the dialogue box appear without an option to choose the quality any ideas  

@ShakarSaleem you should really only use nixtoons2 by now. The source website changed a lot, so nixtoons1 won't be able to play anything. You can safely uninstall it.

> I guess you already looked at SpongeBob, because it's working really good with the dialog box popping up and everything.

@bjgood that's right, 0.2.5 can now get those separate chapters, if the video player page has them.

**Comment by daniel-ntl** [comment]
tried your latest addons and it works, thanks doko, i think this issue are solved and case closed
