### ISSUE TITLE
Paid accounts only?

### ISSUE THREAD

**Issue by rojasj1** [doko-desuka/plugin.video.watchnixtoons2#40]
So how should address this issue should we uninstall and re-install for this to clear out? Downgrade to the previous version? Or register for the premium. Because for some odd reason it works completely fine on my phone I can watch my anime just fine but when I try to use it on my firestick it shows as the source website is temporarily blocked

**Comment by doko-desuka** [comment]
No changes are needed at the moment, it's back to normal, see this discussion:  
https://github.com/doko-desuka/plugin.video.watchnixtoons2/issues/39
