### ISSUE TITLE
Watchnixtoons 2 video quality select

### ISSUE THREAD

**Issue by weapynx** [doko-desuka/plugin.video.watchnixtoons2#42]
There must have been some sort of update, because before every show it asks video quality. You used to be able to change it in settings to auto play highest quality, but that option seems to be gone. How can I avoid having to choose video quality every time

**Comment by doko-desuka** [comment]
Read this please:  
https://github.com/doko-desuka/plugin.video.watchnixtoons2/issues/39#issuecomment-606460809
