### ISSUE TITLE
Any chance you can set content type  different for Cartoons Section

### ISSUE THREAD

**Issue by SerpentDrago** [doko-desuka/plugin.video.watchnixtoons2#43]
![image](https://user-images.githubusercontent.com/21133858/79473805-a1f16400-7fd3-11ea-9ecb-5533935fd6c0.png)

As you can see , the content type for the section(main menu >  Cartoons )    is set to tvshows . as this section is just alphabetical list with no icons / fanart / posters . It looks awful with most skins view for Shows . 

the skin i use (auramod) has ability to lock views to content types . which works great . But not for that section obviously .  

You in the past added ability to set the view ID in settings . but its not applying addon wide , or its the fact that section has a content type set . IDK . 

But i think you can see the issue ?  I would be fine with whatever solution you come up with . Either forcing list for that section / adding artwork / or better yet settings for forcing view id's for those sections . More likely simply removing the content type "tv shows" for that section would work perfectly for my usage .

If wanted i could prob find you a bunch of artwork if you wanted to go that route , though i highly doubt you care to put that much effort into something like this . 

Thanks for all the work you do man . Hope your staying safe .

**Comment by SerpentDrago** [comment]
Just for info , here is how it looks on some of the other views in Auramod 

![image](https://user-images.githubusercontent.com/21133858/79474865-f6491380-7fd4-11ea-8cac-7570125567a3.png)


![image](https://user-images.githubusercontent.com/21133858/79474899-fea14e80-7fd4-11ea-982e-266f4210013e.png)


![image](https://user-images.githubusercontent.com/21133858/79474915-06f98980-7fd5-11ea-9bd1-af796de61135.png)

![image](https://user-images.githubusercontent.com/21133858/79474945-0fea5b00-7fd5-11ea-8c42-72f35e8bb630.png)


![image](https://user-images.githubusercontent.com/21133858/79474992-1e387700-7fd5-11ea-9fbd-cc4af51ce609.png)


![image](https://user-images.githubusercontent.com/21133858/79475019-27294880-7fd5-11ea-9a3b-208d0b9d4a1e.png)

![image](https://user-images.githubusercontent.com/21133858/79475011-24c6ee80-7fd5-11ea-9abf-c939039d184a.png)

**Comment by doko-desuka** [comment]
Hi @SerpentDrago, thanks for the images. I don't remember why it's set to `tvshows`, but if it's not making a practical difference and will look better without, then sure, it can be removed.  
I'll look into it this weekend.

**Comment by doko-desuka** [comment]
Okay, so here's what I thought.

1) You said you think removing the `tvshows` content-type will make it look better on the skin. Have you tried commenting out that line? Maybe it doesn't make a difference, you'd have to test with that skin you're using.

2) Kodi should remember the last view type that you set on that directory. The add-on does not force a specific view.

3) If you want to, you can make 26 images of each alphabet letter for each category, plus one image for the "All" category. We can put the images here on Github and, as long as you turn on a specific setting in the add-on, the catalog folders will use those images as thumbnails.
This means that we don't have to distribute more stuff with the add-on, Kodi can remotely grab those images from the web if the user wants to.  
Each image should be a power-of-two (I suggest 128x128 to keep them light), with a transparent background and a light text color, like white. The image for category "C" for instance, will have a big capital "C" centered on the image, scaled as big as it can but with a margin of about 2 pixels to avoid clipping. I suggest first making letter "W" as it's the widest letter possible, depending on the font.
Example (the background is not transparent on purpose, so it's visible):

![W alphabet folder example (visible background)](https://user-images.githubusercontent.com/31810999/79676564-c3ae3f00-81bd-11ea-827a-0e274c561997.png)

...and how it looks on Kodi (I removed the blue background first, so it's only the letter and drop-shadow):  
![wnt2 category thumbnails](https://user-images.githubusercontent.com/31810999/79676599-11c34280-81be-11ea-81bd-d6634e1ce6e2.png)

**Comment by SerpentDrago** [comment]
The issue with Content type for search being set to shows / movies . is i like to use the LOCK view option in the skin , which locks a view to a content type .. I get i could just not use that lock option . but then i'd need every addon i ever use to let you set the view id , or as you said .. change it for every section lol . 

I'll get a bunch of images for you , that would be great . 

Any particular font you want to use ?

**Comment by SerpentDrago** [comment]
https://github.com/SerpentDrago/resource.images.letters

will that work ? i can make it into a proper resource pack if needed ? or whatever you would like to do . 

Thanks . 

If you have any issues let me know

**Comment by doko-desuka** [comment]
Oh yeah, you made images for the "#" and "All" categories, I had forgotten about them.  

Thanks for the images. There's still need for a fix: in that set that you made, each image has a different size, trimmed to the width and height of each character as they vary.  

Please make them all 128x128 (all images of the same size and with a square format), or else it does not look good (look at the All and I categories for example):
![wnt2 category thumbnails 02](https://user-images.githubusercontent.com/31810999/79714486-5b3b8c80-82a7-11ea-879b-5056a75ca7ae.png)

It's okay if there's empty space, as long as each character is centered on a square of the same size.

**Comment by doko-desuka** [comment]
Actually nevermind, I just batch processed them on PIL.

**Comment by SerpentDrago** [comment]
Perfect , sorry about that . I had forgot about that part of your specification . 

Can you link to the now perfect images . I'll merge into the github so  if others need this set they can use them :)

**Comment by doko-desuka** [comment]
- I don't have any problems with that. Note that I changed the "#" file name to "0" (zero), as # has special meaning in URLs.

- I wouldn't open a vector software to work on them, that'd be going out of my way to work on something that I don't personally need.

- Yeah, I put the 128h images in a folder, then scripted a loop to load each with PIL and paste, centered, on a new 128x128 image and overwrite the original file.

**Comment by doko-desuka** [comment]
PS: you can turn these images on in the new setting, "Show Category Thumbails"

**Comment by SerpentDrago** [comment]
> * I don't have any problems with that. Note that I changed the "#" file name to "0" (zero), as # has special meaning in URLs.
> * I wouldn't open a vector software to work on them, that'd be going out of my way to work on something that I don't personally need.
> * Yeah, I put the 128h images in a folder, then scripted a loop to load each with PIL and paste, centered, on a new 128x128 image and overwrite the original file.

ohh I used the automated ability of AI (i didn't manually make them that would be mad lol ) 



by the way latest update is not installing (downloaded both github zipball and tried just zip you throw in them . 

```
2020-04-20 11:08:55.964 T:6336   ERROR: Failed to parse 'zip://C%3a%5cUsers%5cSerpe%5cDownloads%5cplugin.video.watchnixtoons2-master.zip/plugin.video.watchnixtoons2-master/addon.xml'
2020-04-20 11:09:38.265 T:6336   ERROR: Failed to parse 'zip://C%3a%5cUsers%5cSerpe%5cDownloads%5cplugin.video.watchnixtoons2-0.4.7.zip/plugin.video.watchnixtoons2/addon.xml'
```

**Comment by SerpentDrago** [comment]
#46

**Comment by SerpentDrago** [comment]
by the way , thank you , looking much better . now i just need a generic Fanart used for the menus lol . Its all good though . at least its much easier and quicker to read this way . and does look better then it did :) 

Thanks for all the work man !

![image](https://user-images.githubusercontent.com/21133858/79768615-09235700-82f9-11ea-9898-bb6088294ed2.png)

**Comment by SerpentDrago** [comment]
by the way i'll be more likely using it this way so its all good 

![image](https://user-images.githubusercontent.com/21133858/79770750-d29b0b80-82fb-11ea-87dc-dbd9630f47da.png)
