### ISSUE TITLE
playback error

### ISSUE THREAD

**Issue by AdminZo21** [doko-desuka/plugin.video.watchnixtoons2#48]
Hi.

I was watching Black Clover Eng Dub without any problems for first 7 episodes. When I tried to play episode 8, it gave me this error.

Here is the log (I installed Log Viewer for Kodi and this is what it shows me after I try to play the link):

2020-04-26 12:01:55.179 T:9519 ERROR: EXCEPTION Thrown (PythonToCppException): -->Python callback/script returned the following error<--
-NOTE: IGNORING THE CAN LEAD TO MEMORY LEAKS!
Error type: <type 'exceptions.AttributeError'>
Error Contents: 'NoneType' object has no attribute 'group'
Traceback (most recent call last): file "/storage/emulated/0/Android/data/org.xbmx.kodi/files/.kodi/addons/pluging.video(can't see more) line 4, in <module>
main() # See botom of Plugin,py.
file "/storage/emulated/0/Android/data/org.xbmx.kodi/files/.kodi/addons/pluging.video(can't see more) line 1523, in main
globals ()[[arams.get('action','actionMenu')](params) # Defaultsto 'actionMenu()'.
file "/storage/emulated/0/Android/data/org.xbmx.kodi/files/.kodi/addons/pluging.video(can't see more) line 1297, in actionResolve
sourcesBlock = re.search('sources:\s*?\[(.*?)\}', html, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
-->End of Python script error report<--

**Comment by rcjrulz** [comment]
Think the paywall issue is back.

**Comment by bjgood** [comment]
Yes, I think so, too. It started for us late last night.

**Comment by PepperHomie** [comment]
It is the pay wall issue. Seems to be associated with most things in English. I suggest subbed anime for now

**Comment by AdminZo21** [comment]
I see..

I found a torrent for English Dub and downloaded it on RD server and am watching it with some RD addon.

**Comment by doko-desuka** [comment]
It is the paywall issue indeed, thanks for the notice.  
I had added a warning message when that happens, so that it's less misterious to you why the add-on failed to play, but it wasn't kicking in.  
I now fixed that in version 0.4.9 (no changes other than making the warning actually appear when this temporary block on free videos happens).
