### ISSUE TITLE
Available Enhancement to use wco premium site

### ISSUE THREAD

**Issue by christianhaitian** [doko-desuka/plugin.video.watchnixtoons2#49]
Greetings,

I really like this addon and the website and I want to support the site as it has the most reliable links for dubs and cartoons I've been able to find online so far.  I forked a copy of this repo and modified so that users can provide their own premium account information and use the premium site.  My repo is https://github.com/christianhaitian/plugin.video.watchnixtoons2 and I have a zip there that should just easily update the existing plugin to this one.  It will not work without premium account information provided.  I'm hoping this can be shared with others who care to have this capability.  I am an amateur to novice coder at best so not sure if this plugin will work for others but it works for my use case and I thought I would share it out.  If this is not proper procedure for doing so, my apologies.

**Comment by bjgood** [comment]
Thanks Christian, for your work on this. I was hoping Doko would add this feature. But I'm getting an error...

2020-04-27 08:22:36.141 T:1522520960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Episode list scrape fail: https://www.watchcartoononline.io/anime/spongebob-squarepants
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Default.py", line 4, in <module>
                                                main() # See bottom of Plugin.py.
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Lib/Plugin.py", line 1592, in main
                                                globals()[params.get('action', 'actionMenu')](params) # Defaults to 'actionMenu()'.
                                              File "/storage/.kodi/addons/plugin.video.watchnixtoons2/Lib/Plugin.py", line 328, in actionEpisodesMenu
                                                raise Exception('Episode list scrape fail: ' + url)
                                            Exception: Episode list scrape fail: https://www.watchcartoononline.io/anime/spongebob-squarepants
                                            -->End of Python script error report<--
2020-04-27 08:22:36.279 T:1556960128   ERROR: GetDirectory - Error getting plugin://plugin.video.watchnixtoons2/?action=actionEpisodesMenu&url=https%3a%2f%2fwww.watchcartoononline.io%2fanime%2fspongebob-squarepants
2020-04-27 08:22:36.282 T:1937549760   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.watchnixtoons2/?action=actionEpisodesMenu&url=https%3a%2f%2fwww.watchcartoononline.io%2fanime%2fspongebob-squarepants) failed

I don't know if it's an error on your part, or not. Maybe Doko can take a look at the code.

Let me also add that I did create an account with WatchCartoonOnline but I did not setup reoccurring payments with them via PayPal. So, I guess I don't have a premium account with them (which could be causing  the error). If they would only let you pay for a month, 3 months, six months, or a year yourself, without requiring reoccurring payments, then I'd be all-in. Reoccurring payments is a big no-no to me.

Later...

**Comment by doko-desuka** [comment]
@christianhaitian thanks for the fork, I'll take a look at it.

**Comment by bjgood** [comment]
Christian,
Just to update. I made the plunge and signed up for premium, but I'm still getting the same error.

Later...

**Comment by christianhaitian** [comment]
> Christian,
> Just to update. I made the plunge and signed up for premium, but I'm still getting the same error.
> 
> Later...

I was able to load SpongeBob episodes without issue just now.  Did you make sure to install my zip and then make sure to provide your account’s username and password from this addon's setting menu on the interface screen?  Also make sure you entered this information correctly.  If so, then go to the tools section and click on clear cookies.  You must be a premium subscriber for my addon to work for you.  Otherwise, it will just error out like what you’re getting.

**Comment by PepperHomie** [comment]
Glad to see people actively trying to solve the premium issue. It's a big bummer. Idea though. If one user paid for the premium and we just coded it to use that information every time then we should all be able to use the addon no issue. I suggest a patreon be setup and have doko apply payment for a year or whatever their options are. That's if you trust the guy. Obviously we would need to test to see if multiple users could use the account info at once but us as a group, we could get together to figure that out to see if it's a viable solution. I think all of us would be more than happy to donate for a permanent solution.

**Comment by bjgood** [comment]
Christian,
I found the problem. It turned out to be a faulty favourites.xml file that didn't like your version of WatchNixtoons2. :). To fix it I had to search for each of our favorite cartoon series and save it to Kodi Favourites. From there each series would open and episodes would play.

Everything is working now. Sorry for the trouble.

Thanks, Christian, for the new feature.

**Comment by christianhaitian** [comment]
At less that $3.00 per month, the cost seems very reasonable for the amount of content you get and the reliability.  Also, you can cancel the subscription at any time.  I think it's worth that anyone who wants an affordable and reliable solution for subs, dubs, and cartoons, pay the low fee.  Just my opinion.

**Comment by PepperHomie** [comment]
3 dollars a month vs free? I would never pay for their service. Plenty of other sites offering the same for free

**Comment by christianhaitian** [comment]
If there's an addon for the others that reliably streams the content to Kodi without ads, please share.  I've tried many of them out there and some sites are just terrible with ads and none have had a more reliable addon experience than this one has so far with the bonus of having cartoons.  Wonderfulsubs is pretty good for anime but the development of the addon stopped.  I know doko has an addon available for it but this one just fits my needs great so far.

**Comment by PepperHomie** [comment]
If you can't find a reliable site then that's on you. Don't come one here and act like you care about the addon when I offered a proper solution to fix the addon for all users. A large majority of the users don't get on here.

**Comment by christianhaitian** [comment]
Sharing account info through any addon is not a proper solution.  Especially if it can't be done securely.  Sorry to hurt your feelings.

**Comment by christianhaitian** [comment]
Closing due to not being an issue but sharing a potential solution or workaround.

**Comment by PepperHomie** [comment]
Definetly could be done securely. Again you clearly don't care about this addon.

**Comment by doko-desuka** [comment]
@christianhaitian If you're gonna distribute that fork around, I suggest renaming it so that people aren't confused ("is this the official one, or the modified one?"). Different names will help people differentiate.

I wouldn't have time to manage a single account for everyone to use, that's way more effort than I can spend right now which is close to none. Also, we don't know if their system would allow this kind of simultaneous use -- if it detects many different IP addresses using the same credentials then they could ban that account.  

Is registration disabled? I tried going to https://user.wco.tv/wp-login.php?action=register but it said "User registration is currently not allowed."

**Comment by bjgood** [comment]
Doko,
I doubt if it relates, but I can still login even though "User registration is currently not allowed" is showing at that address you linked to.

Have you thought about incorporating Christian's premium code into WatchNixtoons 2?

Also when you mentioned credentials are you referring to username and password?

Later, bud.

**Comment by doko-desuka** [comment]
I think it's useful to add premium account support.  

But without being able to register for that, I won't have the credentials (indeed, the username and password) to log in and debug how it works. I wouldn't just copy and paste the code because there's some parts that I think can be written differently (I think the cookie expiration date could be used to tell when it'll become invalid, as well as using `ADDON.setSetting()` instead of a file to store the cookie, and only logging in when absolutely necessary).

**Comment by christianhaitian** [comment]
Thanks for the suggestion doko.  I’m hoping not to distribute this one as i’m sure if you incorporate premium login into Your code, my fork can be deprecated.  It has no other benefit and as you point out, it’s not the most efficient.
