### ISSUE TITLE
Show info

### ISSUE THREAD

**Issue by XxkingkrowxX** [doko-desuka/plugin.video.watchnixtoons2#50]
Is there any way to get the add on to automatically get the show info, or add that ability cause it is a pain having to bring up context menu and request show info for them individually?

**Comment by AdminZo21** [comment]
this addon also needs to be able to connect to myanimelist or kitsu to create "Watching now" and "Want to Watch" categories

**Comment by Goldenfreddy0703** [comment]
Hey there, ok so sadly thier is not but if you are using a Auramod or Artic horizon, you could create widgets of the anime categories and you can add fanart tv to them by using an api in your settings. The best thing I suggest is using Auramod and setting up the addon thier or depending on what skin your using, you could change the view layout of how you look at anime and you can lock the view so it works with any anime you find so that you can look at the information of what it's about so its easier for you so that way, when your scrolling thru the anime, the information is thier for you.

**Comment by Goldenfreddy0703** [comment]
Hey i almost forget but here are some great examples of my interface in which show you the information and which is part of a view layout that's locked.
![image](https://user-images.githubusercontent.com/62456796/80899180-31d52480-8cdb-11ea-8b4f-6b36a791f8fa.png)
![image](https://user-images.githubusercontent.com/62456796/80899181-3568ab80-8cdb-11ea-9464-1b60309241d8.png)
![image](https://user-images.githubusercontent.com/62456796/80899183-37cb0580-8cdb-11ea-9df3-e7dfcfa3201c.png)

**Comment by Goldenfreddy0703** [comment]
> 
> 
> this addon also needs to be able to connect to myanimelist or kitsu to create "Watching now" and "Want to Watch" categories

Hey AdminZo21, sorry i did not respond to you but i believe that on the my accounts section on the hummingbird addon has a watching now section in their, im not sure if their is want to watch category but im sure the developer will add that in soon if their is not one.

**Comment by AdminZo21** [comment]
> > 
> > 
> > this addon also needs to be able to connect to myanimelist or kitsu to create "Watching now" and "Want to Watch" categories
> 
> Hey AdminZo21, sorry i did not respond to you but i believe that on the my accounts section on the hummingbird addon has a watching now section in their, im not sure if their is want to watch category but im sure the developer will add that in soon if their is not one.  
> Here is an example of one of the categories your looking for : 
> ![image](https://user-images.githubusercontent.com/62456796/80899289-6eede680-8cdc-11ea-91be-e835f0591d3e.png)
> 

Something like that, yeah. So I can create a widget on Auramod.

I am using 2 addons to watch anime. This one and Hummingbird. Hummingbird is better in "creating widgets" aspect, but lacks sources. This addon works almost ALL the time, but finding anime every time you want to watch is a pain.

Don't get me wrong, I am VERY grateful to the developer of this addon. He did a wonderful work.

All this addon needs now is support, I think.

**Comment by Goldenfreddy0703** [comment]
Oh crap this is watchnixtoons issue, I thought this was a hummingbird github issue. I'm sorry man and I'm sorry for the developers for adding a 3rd party addon called hummingbird. 😅

Welp.....use the hummingbird addon if you want information and stuff and it's a wonderful addon for anime, artwork, detail, ratings, and fanart tv. Its litterly the best addon that gives you the full details than WSbeta or Watchnixtoons. I will be honest. I love doko's addons but I only use them for emergency incase hummingbird shutdown or thier is maintenance or if I cant load a stream. That's litterly all I use it for.

**Comment by doko-desuka** [comment]
> Is there any way to get the add on to automatically get the show info, or add that ability cause it is a pain having to bring up context menu and request show info for them individually?

Hi. There are a couple of problems in the way:  

1. The catalogs in the source website only show the links and names of shows, nothing else (no thumbnails or other metadata). The metadata for a show is on the page for that show, so the only way to get to it is to do an extra web request for that page. If this was done on a big list of 100 items, that would be 100 different page requests (per user), with hundreds of users this would be like a DDoS attack on that humble cartoon website. So the best way to retrieve metadata for all shows would be to try to search for each show on some database like MAL for anime and TVDB for cartoons.  
2. I have no more time or interest in working on add-ons. The watchcartoononline site is right there, so anyone is free to fork this / start from scratch and put all the features they need.

**Comment by Goldenfreddy0703** [comment]
I will be honest, I think the dev is basically making 3rd party addons for websites like wonderfulsub and Watchnixtoons thru Api keys and stuff which is why he the fanart is off and there is no information on each anime but it works like it's a streaming network just not with information or impressive fanart becouse he is pretty much taking the streams from those only two websites which is why this addon mostly works in most cases. I support his addon, I just wish he can add information and fanart to his addons like what the wonderfulsubs did to thier old addon that is surprisingly still working even tho its kinda down.

**Comment by Goldenfreddy0703** [comment]
> > Is there any way to get the add on to automatically get the show info, or add that ability cause it is a pain having to bring up context menu and request show info for them individually?
> 
> Hi. There are a couple of problems in the way:  
> 
> 1. The catalogs in the source website only show the links and names of shows, nothing else (no thumbnails or other metadata). The metadata for a show is on the page for that show, so the only way to get to it is to do an extra web request for that page. If this was done on a big list of 100 items, that would be 100 different page requests (per user), with hundreds of users this would be like a DDoS attack on that humble cartoon website. So the best way to retrieve metadata for all shows would be to try to search for each show on some database like MAL for anime and TVDB for cartoons.  
> 2. I have no more time or interest in working on add-ons. The watchcartoononline site is right there, so anyone is free to fork this / start from scratch and put all the features they need.

Woah...sorry for taking myself too far man. I did not know that would make you mad. I still support your addons man and I love what you been doing in the community but it's my mistake for talking about the hummingbird addon and I admit it so sorry man. I thought this was the hummingbird issue section after all I support both you guys becouse you guys are the best to provide this anime.
