### ISSUE TITLE
[Request] Custom view  / ability to force view type 

### ISSUE THREAD

**Issue by SerpentDrago** [doko-desuka/plugin.video.watchnixtoons2#6]
As this addon deals with lots of content that proper meta data / titles can not be provided , it would help if i could set this addon to use different view types in my skin then most addons . 

Custom view type id's per content type , or the ability to force program / list view in all menus would be extremely helpful . I tend to run view types very very meta data content / poster heavy , and it honestly looks horrid with this addon . 

Thanks Doko for giving life to this great addon again , my kid thanks you for the toons !

**Comment by doko-desuka** [comment]
Hi SerpentDrago,  
the original watchnixtoons hardcoded things to grid view. I did the same in this one, and some people complained because of that ("it's hardcoded to grid view, and I like to use WideList view").  
So I removed any fixed view type.

Kodi remembers the view types that you set on the directories that you visit. This way people can use the view types that they prefer.

I don't plan on adding hardcoded view types. In any case this can be done by editing the source (search for the word "grid" in Plugin.py, there's a comment in there).

**Comment by SerpentDrago** [comment]
"Kodi remembers the view types that you set on the directories that you visit. This way people can use the view types that they prefer."

This is not a solution , as  kodi remembers the view you set PER CONTENT type . not per addon / exact path / directory . 

What i like to use in most addons that can provide proper meta data , is NOT what i would want to use  for the same content type in Nixtoons2 . 

I'd rather not have to fork your addon for such a simple change . 


IS there no way you can at least let us set the view type thats hardcoded in settings option  ? so not per content but just stick to one thing in the whole addon ?

**Comment by SerpentDrago** [comment]
Tried changing that line to 

xbmc.executebuiltin('Container.SetViewMode(50)')

for List view for aura . Doesn't appear to work , looking at it now .  I don not have aura set to lock any views , yet the addon keeps using whatever view type i last set, instead of forcing list for this addon

**Comment by SerpentDrago** [comment]
Ended up having to set the content type  to none for all , to get everything working well enough didn't even use that command . 

Any reason that above command doesn't seem to work though ?

**Comment by SerpentDrago** [comment]
welp , now nothing will play .. guess it needs a mediatype set .. ugg lols ,

**Comment by SerpentDrago** [comment]
I made the mod , and it works great , Just be nice if the addon had the ability built in .  Guess i'll throw this on my repo and keep updated with your changes

**Comment by doko-desuka** [comment]
There's no standard for skins, so each one is free to set their own view types, and that's what makes it complicated to add hardcoded view types -- the view types are numbers, what's to say one type is gonna be recognized by every single skin ever made?

I'm not sure what modifications you made, but you usually need to set the content type (not mediatype, that's a ListItem setting) for the directory, add the directory items, and then execute the "set container view mode".
For example, inside function `actionCatalogSection()`:
```
    xbmcplugin.setContent(PLUGIN_ID, 'episodes')
    (. . .) # Rest of the function.
    xbmc.executebuiltin('Container.SetViewMode(501)') # ID 501 seen in the Aura skin resources.
```
You should add the same to function `actionEpisodeMenu()` and maybe `actionLatestMoviesMenu()`.

More info on xbmcplugin.setContent: https://codedocs.xyz/xbmc/xbmc/group__python__xbmcplugin.html#gaa30572d1e5d9d589e1cd3bfc1e2318d6

**Comment by doko-desuka** [comment]
...and if it wasn't clear, the .setContent call can go as the first line of the function, like in here:   
https://github.com/doko-desuka/plugin.video.ctoonkodi/blob/master/Lib/Plugin.py#L97

**Comment by SerpentDrago** [comment]
the whole point of the ability to set a View ID (and not a named view)  , is the fact that yes skins are different. whats 54 - wide list for me could be square for you .  I'm not asking you to hardcode it , just make it a string/variable  i can enter into the settings page 

if you fire up seren  you will clearly see a great example of how to handle a more complicated version of this . You have the ability for each content type to set a view or custom view id #.  and it forces that just for seren. 

Not all addons display meta data properly . what happens is  some modern skins views look really bad without it as some views are designed around having all that meta data / images . I just want the ability without forking your addon to set it manually JUST for your addon . 

I was not even requesting all that , just the ability to go into the setting of your addon and type in a id that apply s to EVERY directory in the addon . 




Anyways .  your info helps me also cause i like learning how some things are done . Sorry , didn't think it was asking all that much .  


I'll try to figure it out myself . thanks

**Comment by SerpentDrago** [comment]
Sorry if i came across as a prick , i apologize .  Been a long 2 days .

**Comment by doko-desuka** [comment]
You didn't come across as a prike, I just need to say "no" at some point. I wish I could take all requests and make people happy, but I have to think about myself too lol  

There are plenty of people capable of helping with what you asked, they just don't volunteer (at least not for cartoons, Seren has tons of PRs by others, for example).
