### ISSUE TITLE
Watchnixtoons 2 is down

### ISSUE THREAD

**Issue by PepperHomie** [doko-desuka/plugin.video.watchnixtoons2#7]
The anime shows up but when the episodes try to start it stops and back out.

**Comment by doko-desuka** [comment]
What anime? I need series name, season and episode.

**Comment by PepperHomie** [comment]
All of one punch man season 1 dubbed

**Comment by doko-desuka** [comment]
Seems to fail at random, but if you try again it plays. Episode 1, 2 and 3 started to play.

**Comment by PepperHomie** [comment]
I have tried episode 1, 10 time straight and no luck

**Comment by doko-desuka** [comment]
The server might be banning your IP after too many fast tries, 10 times is a lot.  
Also, try setting the quality setting to "use lowest quality".

**Comment by PepperHomie** [comment]
I waited a minute between all tries and tried it with both qualities so what's the issue with the source?

**Comment by doko-desuka** [comment]
I tested just now on my Android TV box and ep. 3 of that show worked, so I'm not sure what's going on on your end.  
Are you able to visit the source website (link in this repo main page) and watch it through there, does it work when you do that?

**Comment by PepperHomie** [comment]
Yes I can watch it on the website. Can you get episode 1 working? I have 2 friends with the same issue

**Comment by PepperHomie** [comment]
All anime is currently down right now. Tried watch dororo episode 15 and the same issue

**Comment by doko-desuka** [comment]
Ooph... someone also reported something like that on an iPad.  

I changed the media grabbing code a bit, but I don't think it's going to do much difference because it was working here before (on Windows 8, and Android TV box), and still works with the change. I tested a few episodes of "Dororo English Subbed".  

Can you share your Kodi log in Debug mode? (you turn that on in the System -> Logging settings, then try to watch any episode to make it fail, then quit Kodi and get the log file and send it to my email: dokodesuka121 at gmail dot com).

**Comment by doko-desuka** [comment]
Okay, here's my assessment: sometimes the video player on the source website itself fails, so it's inconsistent. That being said, I found a problem in the code and I fixed it.  
It's working here, so I'm going to close this issue. If you or friends still have problems, please proceed with Kodi logs (at least the end of the log, where it fails).

**Comment by rojasj1** [comment]
Is Watchnixtoons 2 Down ? For some reason its unresponsive it days there is an error

**Comment by doko-desuka** [comment]
The source site seems to be online. Look in your log for the error message so we can know what it is.

**Comment by PepperHomie** [comment]
I can confirm that my addon is working fine. Maybe his version isnt updated to the recent version

**Comment by doko-desuka** [comment]
@PepperHomie thanks for the confirmation.  

@rojasj1 make sure you're using the latest version. You can get it from [my repository](https://github.com/doko-desuka/doko.repository/releases) after you install it in Kodi (you can also enable auto-updates on it), or by manually downloading [this zip file of WNT2 version 0.3.7](https://github.com/doko-desuka/plugin.video.watchnixtoons2/raw/master/plugin.video.watchnixtoons2-0.3.7.zip) and installing it in Kodi.

**Comment by rojasj1** [comment]
Thank you seems to be working now btw Very Awsome repository! I have
reccomended it to a lot of people

**Comment by doko-desuka** [comment]
@rojasj1 thanks for the compliment, but maybe we should keep it to ourselves? If tons of people end up using WNT2, the source website from which it grabs videos will have to add a Google captcha to cut down on the Kodi traffic (as it's impossible to bypass).  
We should treat this as a scarce resource.

**Comment by rojasj1** [comment]
Your right

**Comment by major48** [comment]
First i was having problems playing any anime. I would have to try over and over. Tonight i decided to wipe kodi and reload it. I installed WNT2 from the Doko repo and now when i click dubbed anime it fails
